AWSTemplateFormatVersion: 2010-09-09
Description: Working with custom resources and S3

Parameters:
  LayerName:
    Type: String
  Description:
    Type: String
  LambdaLayerS3Bucket:
    Type: String
  LambdaLayerKey:
    Type: String

Resources:
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      Content:
        S3Bucket: !Ref LambdaLayerS3Bucket
        S3Key: !Ref LambdaLayerKey
      LayerName: !Ref LayerName
      Description: !Ref Description